---
all:
  vars:
    ansible_user: vagrant
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3

  children:
    elk_servers:
      hosts:
        elk-server:
          ansible_host: 192.168.56.10
          ansible_port: 22
          ansible_ssh_private_key_file: /home/goodsignal/homelab/vagrant/.vagrant/machines/elk-server/virtualbox/private_key

    clients:
      hosts:
        ubuntu-client:
          ansible_host: 192.168.56.20
          ansible_port: 22
          ansible_ssh_private_key_file: /home/goodsignal/homelab/vagrant/.vagrant/machines/ubuntu-client/virtualbox/private_key

    attackers:
      hosts:
        kali-attacker:
          ansible_host: 192.168.56.50
          ansible_port: 22
          ansible_ssh_private_key_file: /home/goodsignal/homelab/vagrant/.vagrant/machines/kali-attacker/virtualbox/private_key
