---
elasticsearch_version: "8.11.0"
elasticsearch_cluster_name: "soc-lab-cluster"
elasticsearch_node_name: "elk-server-node"
elasticsearch_network_host: "0.0.0.0"
elasticsearch_http_port: 9200

# Security credentials
elasticsearch_password: "ElkL@b2025"
