$ANSIBLE_VAULT;1.1;AES256
65396461376265343565373938306334333961386361336634653933323834313532306236353333
3737633762396435383964363166313239376433656564630a623233663964633335306437373230
66656536386639376665643265663166626162656638353062666161303738306632653139323632
6536643037306536640a336335666331306539306239653338363564666334313730666536636663
36373539376630343661633430666637393739323430346464313637656231326665363165646333
63646264383261303833313132646166316263336163613032636632333563643430333834393061
31653263643930633234643136306237666634356135353539303165333732323063613434623030
30353737366236396361323037363331323363376565666435666436663961613438336632333935
32646533666434303334626633323465356665663330656436623333393933616333303939306265
32383262383032616361363266346333396635616430323338666638353561323831323265356331
38396161316333306432666533613131346265303235613234323533356166373461663165353539
37633034653063666161656638366136313937643535346638366232613332346264363564373138
39653764656436633838363666356261386464336538663839656232353465643761346535666336
63326234616661353332643930313562613632336330633833616132316265623864316265303866
36323330393965626436646438346161656533396532313030663934396265373035353233353036
38666237316666386135656631383738356239333930653935366562333332616534363665643638
65343635343536333635386266633861663865613134643434353336313233613233623735356461
38386162343836666662363661393439343239306466316662623864353036333938383138323630
35643931313837333532386564623061373034316538333732326664353637306664303033386335
64393539303039633662663565653130646566643463313631613864653830633561386166303265
37303263313363626166323063663366623863636336633264363434353964336130646432613361
61336636396132353763396363613364393562323835623062656236396433666562643062343837
64373630356432663438666139656162396361316463393539313638306336353739333737633338
39326634363931613162656135303863323331393631313066333538366463613133313837623435
64326166373066303262636537633031653063626338383630373835636634316239
