---
kibana_version: "8.11.0"
kibana_server_host: "0.0.0.0"
kibana_server_port: 5601
kibana_elasticsearch_hosts: "http://localhost:9200"
elasticsearch_username: "elastic"
elasticsearch_password: "ElkL@b2025"
